version: 2

builds:
  - id: portkey
    main: .
    binary: portkey
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - android
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: android
        goarch: amd64
    flags:
      - -buildmode=pie

archives:
  - id: default
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE

checksum:
  name_template: checksums.txt

signs:
  - id: checksums
    cmd: minisign
    signature: "${artifact}.minisig"
    args:
      - "-S"
      - "-s"
      - "{{ .Env.MINISIGN_KEY_FILE }}"
      - "-m"
      - "${artifact}"
      - "-x"
      - "${signature}"
      - "-t"
      - "portkey {{ .Version }}"
    artifacts: checksum
    output: true

release:
  extra_files:
    - glob: ./install.sh
      name_template: install.sh

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^style:"
      - "^test:"
      - "^chore:"
